name: watershed_workflow_CI
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0
  - appdirs=1.4.4
  - attrs=21.2.0
  - boost-cpp=1.74.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - cartopy=0.20.1
  - certifi=2021.10.8
  - cffi=1.15.0
  - cfitsio=4.0.0
  - cftime=1.5.1.1
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - click=8.0.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cryptography=35.0.0
  - curl=7.79.1
  - cycler=0.11.0
  - descartes=1.1.0
  - expat=2.4.1
  - fiona=1.8.20
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - freexl=1.0.6
  - gdal=3.3.3
  - geos=3.10.0
  - geotiff=1.7.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - h5py=3.4.0
  - hdf4=4.2.15
  - hdf5=1.12.1
  - icu=69.1
  - idna=3.1
  - iniconfig=1.1.1
  - jbig=2.1
  - jpeg=9d
  - json-c=0.15
  - kealib=1.4.14
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - lerc=3.0
  - libarchive=3.5.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.79.1
  - libdap4=3.20.6
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgdal=3.3.3
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.43.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libpq=13.3
  - librttopo=1.1.0
  - libspatialite=5.0.1
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libwebp-base=1.2.1
  - libxml2=2.9.12
  - libzip=1.8.0
  - libzlib=1.2.11
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - lzo=2.10
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - meshpy=2020.1
  - more-itertools=8.10.0
  - munch=2.5.0
  - ncurses=6.2
  - netcdf4=1.5.8
  - nspr=4.32
  - nss=3.71
  - numpy=1.21.4
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.2
  - pandas=1.3.4
  - pcre=8.45
  - pillow=8.3.2
  - pip=21.3.1
  - pixman=0.40.0
  - pluggy=1.0.0
  - poppler=21.09.0
  - poppler-data=0.4.11
  - postgresql=13.3
  - proj=8.1.1
  - py=1.11.0
  - pycparser=2.21
  - pyopenssl=21.0.0
  - pyparsing=2.4.7
  - pyproj=3.2.1
  - pyshp=2.1.3
  - pysocks=1.7.1
  - pytest=6.2.5
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytools=2021.2.9
  - pytz=2021.3
  - rasterio=1.2.10
  - readline=8.1
  - requests=2.26.0
  - scipy=1.7.1
  - setuptools=58.5.3
  - shapely=1.8.0
  - six=1.16.0
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - sqlite=3.36.0
  - tiledb=2.3.4
  - tk=8.6.11
  - toml=0.10.2
  - tornado=6.1
  - tzcode=2021e
  - tzdata=2021e
  - urllib3=1.26.7
  - wheel=0.37.0
  - xerces-c=3.2.3
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.0
prefix: /Users/Shared/ornldev/code/miniconda3/envs/watershed_workflow_CI-2021-11-08
