name: watershed_workflow_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0
  - alabaster=0.7.12
  - ansiwrap=0.8.4
  - anyio=3.3.4
  - appdirs=1.4.4
  - appnope=0.1.2
  - argon2-cffi=21.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - black=21.10b0
  - bleach=4.1.0
  - boost-cpp=1.74.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - cartopy=0.20.1
  - certifi=2021.10.8
  - cffi=1.15.0
  - cfitsio=4.0.0
  - cftime=1.5.1.1
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - click=8.0.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.4
  - cryptography=35.0.0
  - curl=7.79.1
  - cycler=0.11.0
  - dataclasses=0.8
  - debugpy=1.5.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - descartes=1.1.0
  - docutils=0.16
  - entrypoints=0.3
  - expat=2.4.1
  - fiona=1.8.20
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - freexl=1.0.6
  - gdal=3.3.3
  - geos=3.10.0
  - geotiff=1.7.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - h5py=3.4.0
  - hdf4=4.2.15
  - hdf5=1.12.1
  - icu=69.1
  - idna=3.1
  - imagesize=1.2.0
  - importlib-metadata=4.8.1
  - importlib_resources=5.4.0
  - iniconfig=1.1.1
  - ipykernel=6.4.2
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - jbig=2.1
  - jedi=0.18.0
  - jinja2=3.0.2
  - jpeg=9d
  - json-c=0.15
  - json5=0.9.5
  - jsonschema=4.2.1
  - jupyter_client=7.0.6
  - jupyter_core=4.9.1
  - jupyter_server=1.11.2
  - jupyterlab=3.2.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.8.2
  - kealib=1.4.14
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - lerc=3.0
  - libarchive=3.5.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.79.1
  - libcxx=12.0.1
  - libdap4=3.20.6
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgdal=3.3.3
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - libglib=2.70.0
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.43.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libpq=13.3
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialite=5.0.1
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libwebp-base=1.2.1
  - libxml2=2.9.12
  - libzip=1.8.0
  - libzlib=1.2.11
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - lzo=2.10
  - markupsafe=2.0.1
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.3
  - meshpy=2020.1
  - mistune=0.8.4
  - more-itertools=8.10.0
  - munch=2.5.0
  - mypy_extensions=0.4.3
  - nb_conda=2.2.1
  - nb_conda_kernels=2.3.1
  - nbclassic=0.3.4
  - nbclient=0.5.4
  - nbconvert=6.2.0
  - nbformat=5.1.3
  - nbsphinx=0.8.7
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - netcdf4=1.5.8
  - notebook=6.4.5
  - nspr=4.32
  - nss=3.71
  - numpy=1.21.4
  - numpydoc=1.1.0
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.0
  - pandas=1.3.4
  - pandoc=2.16.1
  - pandocfilters=1.5.0
  - papermill=2.3.3
  - parso=0.8.2
  - pathspec=0.9.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.3.2
  - pip=21.3.1
  - pixman=0.40.0
  - platformdirs=2.3.0
  - pluggy=1.0.0
  - poppler=21.09.0
  - poppler-data=0.4.11
  - postgresql=13.3
  - proj=8.1.1
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.22
  - ptyprocess=0.7.0
  - py=1.11.0
  - pycparser=2.21
  - pygments=2.10.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.5
  - pyproj=3.2.1
  - pyrsistent=0.18.0
  - pyshp=2.1.3
  - pysocks=1.7.1
  - pytest=6.2.5
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytools=2021.2.9
  - pytz=2021.3
  - pyyaml=6.0
  - pyzmq=22.3.0
  - rasterio=1.2.10
  - readline=8.1
  - regex=2021.11.2
  - requests=2.26.0
  - scipy=1.7.1
  - send2trash=1.8.0
  - setuptools=58.5.3
  - shapely=1.8.0
  - six=1.16.0
  - sniffio=1.2.0
  - snowballstemmer=2.1.0
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - sphinx=4.2.0
  - sphinx_rtd_theme=1.0.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sqlite=3.36.0
  - tenacity=8.0.1
  - terminado=0.12.1
  - testpath=0.5.0
  - textwrap3=0.9.2
  - tiledb=2.3.4
  - tk=8.6.11
  - toml=0.10.2
  - tomli=1.2.2
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.1
  - typed-ast=1.4.3
  - typing_extensions=3.10.0.2
  - tzcode=2021e
  - tzdata=2021e
  - urllib3=1.26.7
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.57.0
  - wheel=0.37.0
  - xerces-c=3.2.3
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.5.0
prefix: /Users/Shared/ornldev/code/miniconda3/envs/watershed_workflow_dev-2021-11-08
